// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: engine.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum EngineCallID: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case getVersion // = 1
  case initialize // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .getVersion
    case 2: self = .initialize
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .getVersion: return 1
    case .initialize: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [EngineCallID] = [
    .unspecified,
    .getVersion,
    .initialize,
  ]

}

public struct EngineVersion: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  public var etag: String {
    get {return _storage._etag ?? String()}
    set {_uniqueStorage()._etag = newValue}
  }
  /// Returns true if `etag` has been explicitly set.
  public var hasEtag: Bool {return _storage._etag != nil}
  /// Clears the value of `etag`. Subsequent reads from it will return its default value.
  public mutating func clearEtag() {_uniqueStorage()._etag = nil}

  public var sha: String {
    get {return _storage._sha ?? String()}
    set {_uniqueStorage()._sha = newValue}
  }
  /// Returns true if `sha` has been explicitly set.
  public var hasSha: Bool {return _storage._sha != nil}
  /// Clears the value of `sha`. Subsequent reads from it will return its default value.
  public mutating func clearSha() {_uniqueStorage()._sha = nil}

  public var url: String {
    get {return _storage._url ?? String()}
    set {_uniqueStorage()._url = newValue}
  }
  /// Returns true if `url` has been explicitly set.
  public var hasURL: Bool {return _storage._url != nil}
  /// Clears the value of `url`. Subsequent reads from it will return its default value.
  public mutating func clearURL() {_uniqueStorage()._url = nil}

  public var next: EngineVersion {
    get {return _storage._next ?? EngineVersion()}
    set {_uniqueStorage()._next = newValue}
  }
  /// Returns true if `next` has been explicitly set.
  public var hasNext: Bool {return _storage._next != nil}
  /// Clears the value of `next`. Subsequent reads from it will return its default value.
  public mutating func clearNext() {_uniqueStorage()._next = nil}

  public var releaseDate: String {
    get {return _storage._releaseDate ?? String()}
    set {_uniqueStorage()._releaseDate = newValue}
  }
  /// Returns true if `releaseDate` has been explicitly set.
  public var hasReleaseDate: Bool {return _storage._releaseDate != nil}
  /// Clears the value of `releaseDate`. Subsequent reads from it will return its default value.
  public mutating func clearReleaseDate() {_uniqueStorage()._releaseDate = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "asyncify.engine"

extension EngineCallID: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CALL_ID_UNSPECIFIED"),
    1: .same(proto: "CALL_ID_GET_VERSION"),
    2: .same(proto: "CALL_ID_INITIALIZE"),
  ]
}

extension EngineVersion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Version"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .same(proto: "etag"),
    4: .same(proto: "sha"),
    5: .same(proto: "url"),
    6: .same(proto: "next"),
    7: .standard(proto: "release_date"),
  ]

  fileprivate class _StorageClass {
    var _id: String = String()
    var _name: String = String()
    var _etag: String? = nil
    var _sha: String? = nil
    var _url: String? = nil
    var _next: EngineVersion? = nil
    var _releaseDate: String? = nil

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _name = source._name
      _etag = source._etag
      _sha = source._sha
      _url = source._url
      _next = source._next
      _releaseDate = source._releaseDate
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._etag) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._sha) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._url) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._next) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._releaseDate) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      try { if let v = _storage._etag {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._sha {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._url {
        try visitor.visitSingularStringField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._next {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._releaseDate {
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: EngineVersion, rhs: EngineVersion) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._etag != rhs_storage._etag {return false}
        if _storage._sha != rhs_storage._sha {return false}
        if _storage._url != rhs_storage._url {return false}
        if _storage._next != rhs_storage._next {return false}
        if _storage._releaseDate != rhs_storage._releaseDate {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
