// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: engine.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class WAEngineVersion;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum WAEngineCallID

typedef GPB_ENUM(WAEngineCallID) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  WAEngineCallID_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  WAEngineCallID_CallIdUnspecified = 0,
  WAEngineCallID_CallIdGetVersion = 1,
  WAEngineCallID_CallIdInitialize = 2,
};

GPBEnumDescriptor *WAEngineCallID_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL WAEngineCallID_IsValidValue(int32_t value);

#pragma mark - WAEngineEngineRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface WAEngineEngineRoot : GPBRootObject
@end

#pragma mark - WAEngineVersion

typedef GPB_ENUM(WAEngineVersion_FieldNumber) {
  WAEngineVersion_FieldNumber_Id_p = 1,
  WAEngineVersion_FieldNumber_Name = 2,
  WAEngineVersion_FieldNumber_Etag = 3,
  WAEngineVersion_FieldNumber_Sha = 4,
  WAEngineVersion_FieldNumber_URL = 5,
  WAEngineVersion_FieldNumber_Next = 6,
  WAEngineVersion_FieldNumber_ReleaseDate = 7,
};

GPB_FINAL @interface WAEngineVersion : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *etag;
/** Test to see if @c etag has been set. */
@property(nonatomic, readwrite) BOOL hasEtag;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sha;
/** Test to see if @c sha has been set. */
@property(nonatomic, readwrite) BOOL hasSha;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@property(nonatomic, readwrite, strong, null_resettable) WAEngineVersion *next;
/** Test to see if @c next has been set. */
@property(nonatomic, readwrite) BOOL hasNext;

@property(nonatomic, readwrite, copy, null_resettable) NSString *releaseDate;
/** Test to see if @c releaseDate has been set. */
@property(nonatomic, readwrite) BOOL hasReleaseDate;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
