// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: music.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class WAMusicAuthor;
@class WAMusicEntry;
@class WAMusicListOptions_Discover;
@class WAMusicListOptions_Search;
@class WAMusicTrack;
@class WAMusicTrackDetails_Format;
@class WAMusicTranscript_Segment;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - WAMusicMusicRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface WAMusicMusicRoot : GPBRootObject
@end

#pragma mark - WAMusicOptions

typedef GPB_ENUM(WAMusicOptions_FieldNumber) {
  WAMusicOptions_FieldNumber_Provider = 1,
};

GPB_FINAL @interface WAMusicOptions : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *provider;

@end

#pragma mark - WAMusicListOptions

typedef GPB_ENUM(WAMusicListOptions_FieldNumber) {
  WAMusicListOptions_FieldNumber_ProvidersArray = 1,
  WAMusicListOptions_FieldNumber_Discover = 2,
  WAMusicListOptions_FieldNumber_Search = 3,
};

GPB_FINAL @interface WAMusicListOptions : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<WAMusicEntry*> *providersArray;
/** The number of items in @c providersArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger providersArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) WAMusicListOptions_Discover *discover;
/** Test to see if @c discover has been set. */
@property(nonatomic, readwrite) BOOL hasDiscover;

@property(nonatomic, readwrite, strong, null_resettable) WAMusicListOptions_Search *search;
/** Test to see if @c search has been set. */
@property(nonatomic, readwrite) BOOL hasSearch;

@end

#pragma mark - WAMusicListOptions_Discover

typedef GPB_ENUM(WAMusicListOptions_Discover_FieldNumber) {
  WAMusicListOptions_Discover_FieldNumber_CategoriesArray = 1,
};

GPB_FINAL @interface WAMusicListOptions_Discover : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<WAMusicEntry*> *categoriesArray;
/** The number of items in @c categoriesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger categoriesArray_Count;

@end

#pragma mark - WAMusicListOptions_Search

typedef GPB_ENUM(WAMusicListOptions_Search_FieldNumber) {
  WAMusicListOptions_Search_FieldNumber_ScopesArray = 1,
};

GPB_FINAL @interface WAMusicListOptions_Search : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *scopesArray;
/** The number of items in @c scopesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger scopesArray_Count;

@end

#pragma mark - WAMusicEntry

typedef GPB_ENUM(WAMusicEntry_FieldNumber) {
  WAMusicEntry_FieldNumber_Id_p = 1,
  WAMusicEntry_FieldNumber_Name = 2,
};

GPB_FINAL @interface WAMusicEntry : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - WAMusicTrackDetails

typedef GPB_ENUM(WAMusicTrackDetails_FieldNumber) {
  WAMusicTrackDetails_FieldNumber_Id_p = 1,
  WAMusicTrackDetails_FieldNumber_Title = 2,
  WAMusicTrackDetails_FieldNumber_Description_p = 3,
  WAMusicTrackDetails_FieldNumber_Author = 4,
  WAMusicTrackDetails_FieldNumber_FormatsArray = 5,
  WAMusicTrackDetails_FieldNumber_Thumbnail = 6,
  WAMusicTrackDetails_FieldNumber_Duration = 7,
  WAMusicTrackDetails_FieldNumber_Views = 8,
  WAMusicTrackDetails_FieldNumber_DashManifestURL = 9,
  WAMusicTrackDetails_FieldNumber_HlsManifestURL = 10,
  WAMusicTrackDetails_FieldNumber_RelatedTracksArray = 11,
};

GPB_FINAL @interface WAMusicTrackDetails : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, strong, null_resettable) WAMusicAuthor *author;
/** Test to see if @c author has been set. */
@property(nonatomic, readwrite) BOOL hasAuthor;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<WAMusicTrackDetails_Format*> *formatsArray;
/** The number of items in @c formatsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger formatsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbnail;
/** Test to see if @c thumbnail has been set. */
@property(nonatomic, readwrite) BOOL hasThumbnail;

@property(nonatomic, readwrite) double duration;

@property(nonatomic, readwrite) int32_t views;

@property(nonatomic, readwrite, copy, null_resettable) NSString *dashManifestURL;
/** Test to see if @c dashManifestURL has been set. */
@property(nonatomic, readwrite) BOOL hasDashManifestURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hlsManifestURL;
/** Test to see if @c hlsManifestURL has been set. */
@property(nonatomic, readwrite) BOOL hasHlsManifestURL;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<WAMusicTrack*> *relatedTracksArray;
/** The number of items in @c relatedTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger relatedTracksArray_Count;

@end

#pragma mark - WAMusicTrackDetails_Format

typedef GPB_ENUM(WAMusicTrackDetails_Format_FieldNumber) {
  WAMusicTrackDetails_Format_FieldNumber_Id_p = 1,
  WAMusicTrackDetails_Format_FieldNumber_URL = 2,
  WAMusicTrackDetails_Format_FieldNumber_Quality = 3,
  WAMusicTrackDetails_Format_FieldNumber_Metadata = 4,
  WAMusicTrackDetails_Format_FieldNumber_MimeType = 5,
  WAMusicTrackDetails_Format_FieldNumber_Exp = 6,
};

GPB_FINAL @interface WAMusicTrackDetails_Format : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quality;
/** Test to see if @c quality has been set. */
@property(nonatomic, readwrite) BOOL hasQuality;

@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *metadata;
/** Test to see if @c metadata has been set. */
@property(nonatomic, readwrite) BOOL hasMetadata;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mimeType;
/** Test to see if @c mimeType has been set. */
@property(nonatomic, readwrite) BOOL hasMimeType;

/** expiry time (epoch time) */
@property(nonatomic, readwrite) int64_t exp;
@property(nonatomic, readwrite) BOOL hasExp;

@end

#pragma mark - WAMusicTranscript

typedef GPB_ENUM(WAMusicTranscript_FieldNumber) {
  WAMusicTranscript_FieldNumber_SegmentsArray = 1,
};

GPB_FINAL @interface WAMusicTranscript : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<WAMusicTranscript_Segment*> *segmentsArray;
/** The number of items in @c segmentsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger segmentsArray_Count;

@end

#pragma mark - WAMusicTranscript_Segment

typedef GPB_ENUM(WAMusicTranscript_Segment_FieldNumber) {
  WAMusicTranscript_Segment_FieldNumber_Text = 1,
  WAMusicTranscript_Segment_FieldNumber_Offset = 2,
  WAMusicTranscript_Segment_FieldNumber_Duration = 3,
};

GPB_FINAL @interface WAMusicTranscript_Segment : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@property(nonatomic, readwrite) int32_t offset;

@property(nonatomic, readwrite) int32_t duration;

@end

#pragma mark - WAMusicAuthor

typedef GPB_ENUM(WAMusicAuthor_FieldNumber) {
  WAMusicAuthor_FieldNumber_Id_p = 1,
  WAMusicAuthor_FieldNumber_Name = 2,
  WAMusicAuthor_FieldNumber_Thumbnail = 3,
};

GPB_FINAL @interface WAMusicAuthor : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbnail;
/** Test to see if @c thumbnail has been set. */
@property(nonatomic, readwrite) BOOL hasThumbnail;

@end

#pragma mark - WAMusicTrack

typedef GPB_ENUM(WAMusicTrack_FieldNumber) {
  WAMusicTrack_FieldNumber_Id_p = 1,
  WAMusicTrack_FieldNumber_Title = 2,
  WAMusicTrack_FieldNumber_Kind = 3,
  WAMusicTrack_FieldNumber_Author = 4,
  WAMusicTrack_FieldNumber_Thumbnail = 5,
};

GPB_FINAL @interface WAMusicTrack : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *kind;

@property(nonatomic, readwrite, strong, null_resettable) WAMusicAuthor *author;
/** Test to see if @c author has been set. */
@property(nonatomic, readwrite) BOOL hasAuthor;

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbnail;
/** Test to see if @c thumbnail has been set. */
@property(nonatomic, readwrite) BOOL hasThumbnail;

@end

#pragma mark - WAMusicListTracks

typedef GPB_ENUM(WAMusicListTracks_FieldNumber) {
  WAMusicListTracks_FieldNumber_ItemsArray = 1,
  WAMusicListTracks_FieldNumber_Continuation = 2,
};

GPB_FINAL @interface WAMusicListTracks : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<WAMusicTrack*> *itemsArray;
/** The number of items in @c itemsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *continuation;
/** Test to see if @c continuation has been set. */
@property(nonatomic, readwrite) BOOL hasContinuation;

@end

#pragma mark - WAMusicListSuggestions

typedef GPB_ENUM(WAMusicListSuggestions_FieldNumber) {
  WAMusicListSuggestions_FieldNumber_SuggestionsArray = 1,
};

GPB_FINAL @interface WAMusicListSuggestions : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *suggestionsArray;
/** The number of items in @c suggestionsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger suggestionsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
